"""Outbound emergency Twilio voice call for Materna.

Credential-gated: if Twilio or the recipient number aren't configured, this logs
and no-ops (returns None) instead of raising — so the demo flow never crashes.
"""

import logging
import uuid
from datetime import datetime

from app.config import get_settings
from app.db.session import SessionLocal
from app.demo_config import DEMO_PATIENT_NAME
from app.models.checkin import CheckupSession
from app.models.user import UserProfile
from app.services.session_metrics import extract_hr, hr_7day_avg

logger = logging.getLogger(__name__)

_FLAG_LABELS = {
    "shortness_of_breath": "shortness of breath",
    "foot_swelling": "foot and ankle swelling",
    "chest_pain": "chest pain",
    "severe_headache": "severe headache",
    "vision_changes": "vision changes",
    "heavy_bleeding": "heavy bleeding",
    "reduced_appetite": "reduced appetite and hydration",
    "reduced_fetal_movement": "reduced fetal movement",
    "mood_concern": "significant mood and anxiety concerns",
}


def _build_twiml(
    name: str,
    check_time: str,
    hr,
    hr_avg,
    flags: list[str],
    quote: str,
    live_transcript: list[str] | None = None,
) -> str:
    # Build a personalized spoken summary from what she actually said in the session.
    if live_transcript:
        # Use the last 3 things she said — most recent and relevant.
        recent_lines = [l.strip() for l in live_transcript[-3:] if l.strip()]
        spoken_lines = " ".join(f'"{line}"' for line in recent_lines)
        her_words_sentence = (
            f"During her check-in, {name} said these exact words: {spoken_lines}. "
            "She is in distress and needs you right now."
        )
    elif quote:
        her_words_sentence = f'In her own words, {name} said: "{quote}". She needs your help immediately.'
    else:
        her_words_sentence = f"{name} asked Materna to contact you. She needs your help right now."

    symptom_list = [_FLAG_LABELS.get(f, f.replace("_", " ")) for f in (flags or [])]
    symptom_sentence = (
        "She also reported: " + ", ".join(symptom_list) + "."
        if symptom_list
        else ""
    )
    hr_text = str(round(hr)) if hr else "unknown"

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Say voice="Polly.Joanna" rate="85%">
    Hello. This is an urgent call from Materna AI about {name}.
    <break time="0.6s"/>
    {name} is currently in her morning health check-in and she needs you immediately.
    <break time="0.5s"/>
    {her_words_sentence}
    <break time="0.5s"/>
    {symptom_sentence}
    Her camera-measured heart rate is {hr_text} beats per minute.
    <break time="0.5s"/>
    Please call {name} right now, or go to her. Do not wait.
    <break time="0.4s"/>
    This message was generated by Materna AI. If this is a medical emergency, call 9 1 1 immediately.
  </Say>
  <Pause length="1"/>
  <Say voice="Polly.Joanna" rate="85%">
    Again — {name} needs you right now. Please reach her immediately.
  </Say>
</Response>"""


def place_emergency_call(
    session_id: str,
    reason: str | None = None,
    live_transcript: list[str] | None = None,
) -> str | None:
    """Background-task entry point. Returns the Twilio call SID, or None if skipped.

    live_transcript: the patient's actual spoken words collected during the session,
    used to make the call message personal and specific.
    """
    settings = get_settings()
    if not (settings.twilio_account_sid and settings.twilio_auth_token):
        logger.warning("Twilio not configured — emergency call skipped (reason=%s)", reason)
        return None
    if not settings.emergency_call_recipient or not settings.twilio_phone_number:
        logger.warning("Emergency recipient/from number not set — call skipped")
        return None

    db = SessionLocal()
    try:
        session = db.get(CheckupSession, uuid.UUID(str(session_id)))
        profile = db.get(UserProfile, session.user_id) if session else None
        name = (profile.first_name if profile and profile.first_name else DEMO_PATIENT_NAME)
        check_time = datetime.now().strftime("%-I:%M %p")
        hr = extract_hr(session) if session else None
        hr_avg = hr_7day_avg(db, profile.id) if profile else None
        flags = (session.symptom_flags or []) if session else []
        quote = (session.patient_quote or "") if session else ""

        twiml = _build_twiml(name, check_time, hr, hr_avg, flags, quote, live_transcript)

        from twilio.rest import Client

        client = Client(settings.twilio_account_sid, settings.twilio_auth_token)
        call = client.calls.create(
            twiml=twiml,
            to=settings.emergency_call_recipient,
            from_=settings.twilio_phone_number,
        )
        session.emergency_call_placed = True
        session.emergency_call_sid = call.sid
        db.commit()
        logger.info("Emergency call placed: sid=%s reason=%s", call.sid, reason)
        return call.sid
    except Exception as exc:  # noqa: BLE001
        logger.error("place_emergency_call failed: %s", exc)
        return None
    finally:
        db.close()
